apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector: 
    matchLabel:
      app: postgre
  template:
    metadata:
      label:
        app: postgre     
    spec: 
      contaniners:
        - name: postgre
        image: postgres:15.0
        ports: 
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "Pg#123"  
        - name: POSTGRES_USER
          value: "kubenews"         
        - name: POSTGRES_DB
          value: "kubenews" 
---
apiVersion: apps/v1
kind: Service
metadata:
  name: postgre          
spec:
  selector: 
    app: postgre
    ports:
      - port: 5432
    type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector: 
    matchLabel:
      app: web
  template:
    metadata:
      label:
        app: web     
    spec: 
      contaniners:
        - name: web
        image: ernestojunior/kube-news:v1
        ports: 
        - containerPort: 8080
        env:
        - name: DB_PASSWORD
          value: "Pg#123"  
        - name: DB_USERNAME
          value: "kubenews"         
        - name: DB_DATABASE
          value: "kubenews"    
        - name: DB_HOST
          value: "postgre"  
---
apiVersion: apps/v1
kind: Service
metadata:
  name: web          
spec:
  selector: 
    app: web
    ports:
      - port: 80
        targetPort: 8080
        NodePort: 30000
    type: NodePort